# Generated by Django 2.0.7 on 2018-08-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('addr_street', models.CharField(blank=True, max_length=250)),
                ('addr_apt', models.CharField(blank=True, max_length=10)),
                ('addr_city', models.CharField(blank=True, max_length=50)),
                ('addr_zip', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
