# Generated by Django 2.0.7 on 2018-08-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
