# Generated by Django 2.1.1 on 2018-10-20 04:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20181019_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_donations', to='child.Child'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donor_donations', to='donor.Donor'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2019, 10, 20)),
        ),
    ]
