# Generated by Django 2.0.7 on 2018-08-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_auto_20180821_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='project',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='child',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
