# Generated by Django 2.1.1 on 2018-11-27 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_auto_20181127_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='child.Child'),
        ),
    ]
