# Generated by Django 2.1.1 on 2018-10-21 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_auto_20181020_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2019, 10, 21)),
        ),
    ]
