# Generated by Django 2.1.1 on 2018-10-06 00:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_auto_20181003_1357'),
        ('donor', '0005_donor_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorship_amount', models.FloatField()),
                ('expiry_date', models.DateField(default=datetime.date(2019, 10, 6))),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='child.Child')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donor.Donor')),
            ],
        ),
    ]
