# Generated by Django 2.1.1 on 2018-10-21 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_auto_20181021_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 21, 16, 23, 28, 74775, tzinfo=utc)),
        ),
    ]
