# Generated by Django 2.0.7 on 2018-08-21 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('contact_name', models.CharField(max_length=250)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=250)),
                ('contact_addr_street', models.CharField(blank=True, max_length=250)),
                ('contact_addr_apt', models.CharField(blank=True, max_length=10)),
                ('contact_addr_city', models.CharField(blank=True, max_length=50)),
                ('contact_addr_state', models.CharField(blank=True, max_length=100)),
                ('contact_addr_zip', models.CharField(blank=True, max_length=6)),
                ('location_addr_street', models.CharField(blank=True, max_length=250)),
                ('location_addr_apt', models.CharField(blank=True, max_length=10)),
                ('location_addr_city', models.CharField(blank=True, max_length=50)),
                ('location_addr_state', models.CharField(blank=True, max_length=100)),
                ('location_addr_zip', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
