# Generated by Django 2.1.1 on 2018-11-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='child_pics/happy_apna_skool_kid.jpg', upload_to='child_pics'),
        ),
    ]
