# Generated by Django 2.1.1 on 2018-09-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='project',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
    ]
