# Generated by Django 2.1.1 on 2018-11-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contact_name',
            new_name='contact_first_name',
        ),
        migrations.AddField(
            model_name='project',
            name='contact_last_name',
            field=models.CharField(default='contact first', max_length=250),
            preserve_default=False,
        ),
    ]
