# Generated by Django 2.1.1 on 2018-11-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20181106_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sponsorship_amount_per_child',
            field=models.FloatField(default=50),
        ),
    ]
