# Generated by Django 2.1.1 on 2018-09-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_project_partner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
