# Generated by Django 2.1.1 on 2018-10-19 23:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_date', models.DateField(default=django.utils.timezone.now)),
                ('milestone', models.CharField(blank=True, max_length=100)),
                ('short_description', models.CharField(max_length=250)),
                ('long_description', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='child.Child')),
            ],
        ),
    ]
