# Generated by Django 2.1.1 on 2018-09-19 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='project_owner_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='project_coord', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
