# Generated by Django 2.1.1 on 2018-10-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='image',
            field=models.ImageField(blank=True, default='https://sv.ashanet.org/wp-content/uploads/sites/45/2014/05/happy_apna_skool_kid.jpg', upload_to='child_pics'),
        ),
    ]
