# Generated by Django 2.1.1 on 2018-09-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_child_project_owner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
