# Generated by Django 2.1.1 on 2018-09-21 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_auto_20180920_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='project_owner_user',
            new_name='project_partner_user',
        ),
    ]
