# Generated by Django 2.1.1 on 2018-11-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_child_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='image',
            field=models.ImageField(blank=True, default='child_pics/happy_apna_skool_kid.jpg', upload_to='child_pics'),
        ),
    ]
